CREATE TABLE DEPT_CODE(CODE VARCHAR(4), NAME VARCHAR(50));
INSERT INTO DEPT_CODE VALUES('CMPN','COMPUTER ENGINEERING');
INSERT INTO DEPT_CODE VALUES('INFT','INFORMATION TECHNOLOGY');
INSERT INTO DEPT_CODE VALUES('BIOM','BIOMEDICAL ENGINEERING');
INSERT INTO DEPT_CODE VALUES('EXTC','ELECTRONICS AND TELECOMMUNICATION ENGINEERING');
INSERT INTO DEPT_CODE VALUES('EXCS','');
SELECT * FROM DEPT_CODE;
ALTER TABLE DEPT_CODE ADD PRIMARY KEY (CODE);
UPDATE DEPT_CODE SET CODE='ETRX',NAME='ELECTRONICS ENGINEERING' WHERE CODE='EXCS';
ALTER TABLE DEPT_CODE RENAME COLUMN CODE TO D_CODE;
ALTER TABLE DEPT_CODE RENAME COLUMN NAME TO D_NAME;

CREATE TABLE CMPN_TEACHER_TABLE(T_CODE VARCHAR(4), T_NAME VARCHAR(50));
INSERT INTO CMPN_TEACHER_TABLE VALUES('SSO','SWAPNIL SHIVAJI SONAWANE');
INSERT INTO CMPN_TEACHER_TABLE VALUES('PV','PANKAJ JAGDISH VANWARI');
INSERT INTO CMPN_TEACHER_TABLE VALUES('AHS','AVINASH HIRALALJI SHRIVAS');
INSERT INTO CMPN_TEACHER_TABLE VALUES('SJN','SUJA JAYACHANDRAN NA');
INSERT INTO CMPN_TEACHER_TABLE VALUES('SB','SUVARNA PARSHURAM BHAT');
INSERT INTO CMPN_TEACHER_TABLE VALUES('SDW','SANJEEV MEWALAL DWIVEDI');
SELECT * FROM CMPN_TEACHER_TABLE;

CREATE TABLE CMPN_UPDATE_TABLE(,T_CODE VARCHAR(4), AVAILABLE BOOLEAN,REASON VARCHAR(1000));